### ISSUE TITLE
Formspree remaining

### ISSUE THREAD

**Issue by ewjoachim** [kdevo/osprey-delight#28]
I might be wrong, but from history.md I saw that this theme didn't have formspree:

https://github.com/kdevo/osprey-delight/blob/9b1fea2b45dc73e9ee45b477ea3011cb879de510/history.md#L18

Though formspree is still the action of the contact form:

https://github.com/kdevo/osprey-delight/blob/9b1fea2b45dc73e9ee45b477ea3011cb879de510/layouts/partials/sections/contact.html#L12

Is this an oversight ? I understand that it's not going to change anything given the form sends contents with Ajax and not with POST, but still :)

**Comment by kdevo** [comment]
It was left in to confuse some spambots, but I fear it's currently [causing more misunderstandings than helping anyone who reads the source code](https://github.com/kdevo/osprey-delight/pull/20), so this will be removed in the upcoming v5.

**Comment by kdevo** [comment]
Closed by https://github.com/kdevo/osprey-delight/commit/b638f28ea93beb1be9aa3408f026c47acbecc3a2
