### ISSUE TITLE
 Add page below the gallery

### ISSUE THREAD

**Issue by MrAntooo** [kdevo/osprey-delight#30]
Hello,
another section similar to the About is possible, under the gallery. I would like to directly add a page.md with other indications and use the shortcode to read a pdf.

**Comment by kdevo** [comment]
Hi @MrAntooo 

docs on this topic will follow. For now please check out this discussion (and newest comments in it): https://github.com/kdevo/osprey-delight/discussions/17

**Comment by kdevo** [comment]
Closed by https://github.com/kdevo/osprey-delight/commit/b638f28ea93beb1be9aa3408f026c47acbecc3a2
