### ISSUE TITLE
google_analytics_async has been removed

### ISSUE THREAD

**Issue by thepowerfulwoz** [kdevo/osprey-delight#53]
The google_analytics_async.html template has been removed from hugo to match the updated google analytics version. changing the name of the file to google_analytics.html should fix it.

**Comment by kdevo** [comment]
Hi @thepowerfulwoz, thanks for the note.
I'll consider this in a next maintenance round.

**Right now, I'm not actively working on the theme, so any PR fixing this is welcome!**
