### ISSUE TITLE
Insert script into head.html

### ISSUE THREAD

**Issue by ChilledChild** [kdevo/osprey-delight#6]
Could there be a function that will insert a script into the html head? Similar to _googleAnalytics_ from config.html, another function such as _headInserts_ would allow a user to embed custom functions without making direct changes to head.html.

**Comment by kdevo** [comment]
Hi @ChilledChild,

thanks for your suggestion.
Technically, this shouldn't be a problem. However, conceptually, there might already be a more elegant built-in Hugo solution.
In my view, the most customizability would be given by including a custom partial HTML in the head that the user can configure (not only limiting to scripts).
I'll look into it when I have time!

**Comment by kdevo** [comment]
Implemented in 88674692c77d324b09f678477ca7f562aaa5b27e (dev)
Makes use of [Hugo's load order for partials](https://gohugo.io/templates/partials/)! :rocket:
