### ISSUE TITLE
About page CSS differs from Osprey

### ISSUE THREAD

**Issue by blutack** [kdevo/osprey-delight#8]
Another small issue that might not be an issue.

While porting my site, I noticed that the "about" content was centered, whereas on my original site the content was left aligned.

The original Osprey uses the following layout for the about section:
```
  <section class="about" id="about">
    <div class="container middle-xs">
      <div class="row center-xs">
        -- title -- 
      </div>
      <div class="row">
        <div class="col-xs-12 middle-xs">
          -- content --
        </div>
      </div>
    </div>
  </section>
```

whereas delight uses the following:

```
  <section class="about" id="about">
    <div class="container middle-xs">
      <div class="row center-xs">
        -- title -- 
      </div>
      <div class="row center-xs"> <- note the center-xs element here, which forces text-align: center
        <div class="col-xs-12 middle-xs">
          -- content --
        </div>
      </div>
    </div>
  </section>
```

It's a small thing but very obvious if you're porting a site, especially one which uses an unordered list in the about section!

Up to you if you want to fix it as I'm not sure how worried about Osprey compatibility you are.

**Comment by kdevo** [comment]
I first thought about providing an additional config param, but actually decided against it, as each additionally introduced param increases the potential for errors and requires extensive tesing.

Hence, I made it more clear via docs and added an example rule within the theme's built-in `_custom.scss` on how to override this to achieve original Osprey theme's text alignment (see above commit).

Regarding my choice of centering this within Osprey Delight:
I am a fan of consistency. It's highly subjective, but my eyes like that both, header as well as content are aligned consistently.

Regarding the Osprey compatibility, I think it's nice if users can migrate more simply to this, but think that these **visual** changes belong to the different interpretation of this theme, which is so to say a feature and not a bug.
Nevertheless, as already mentioned it's easy to restore the original behavior. :smile:
