### ISSUE TITLE
Basin contact requires Params.Contact.select

### ISSUE THREAD

**Issue by blutack** [kdevo/osprey-delight#9]
Sorry for yet another one.

The exampleSite config.yaml says the following:

```
## Configure contact form:
[Params.Contact]
  # [str[]] i18n keys used to display in an additional select box.
  #   Comment out if you want to disable it.
  select = ["generic", "coop", "business", "project"]
```

However, if you comment it out comments won't work because the template correctly doesn't render the dropdown but the javascript assumes `$('select[name=matter]')` always exists on line 21.

I've "fixed it" on my site with the following change to check if there's a matter selection and if not, fall back to an empty string:

`matter = $('select[name=matter]') ? $('select[name=matter]').value : "",`

**Comment by kdevo** [comment]
Thanks for reporting this, definitely a bug!
For prioritizing: Does it affect the contact form's functionality, i.e. did you still receive an e-mail or did the whole contact JS simply fail?

**Comment by blutack** [comment]
You could actually cherry pick in https://github.com/Fluxense/osprey-delight/commit/91977b6eae11c0866d0569601a05418d1ab173c1 if you want a quick and dirty fix.

**Comment by kdevo** [comment]
Thanks for clarifying this @blutack!
I fixed it by introducing an additional template check within the `contact.js`.
In case you want to test this, please checkout the `dev` branch.
